apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customservices.tutorial.myfirstoperator
spec:
  group: tutorial.myfirstoperator
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      # Aschema is required
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: # Root field 'spec'
              type: object  # It is an object
              properties:
                name:
                  type: string
                label:
                  type: string
  scope: Namespaced
  names:
    plural: customservices
    singular: customservice
    kind: CustomService
    shortNames:
      - csvc