apiVersion: locust.io/v1
kind: LocustTest
metadata:
  name: demo.test
spec:
  image: locustio/locust:latest
  masterCommandSeed: --locustfile /lotest/src/locust_project_demo.py
  workerCommandSeed: --locustfile /lotest/src/locust_project_demo.py
  workerReplicas: 3
  configMap: test-map
