apiVersion: locust.io/v1
kind: LocustTest
metadata:
  name: demo.test
spec:
  image: locustio/locust:latest

  # [Optional-Section] Labels
  labels:
    master:
      locust.io/role: "master"
      myapp.com/testId: "abc-123"
      myapp.com/tenantId: "xyz-789"
    worker:
      locust.io/role: "worker"

  # [Optional-Section] Annotations
  annotations:
    master:
      myapp.com/threads: "1000"
      myapp.com/version: "2.1.0"
    worker:
      myapp.com/version: "2.1.0"


  # [Optional-Section] Affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        organisation.com/nodeAffinityLabel1: locust-cloud-tests
        organisation.com/nodeAffinityLabel2: performance-nodes
        organisation.com/nodeAffinityLabel3: high-memory

  # [Optional-Section] Taint tolerations
  tolerations:
    - key: taint-A
      operator: Equal
      value: ssd
      effect: NoSchedule
    - key: taint-B
      operator: Exists
      effect: NoExecute

  masterCommandSeed:
    --locustfile /lotest/src/locust_project_demo.py
    --host https://docs.locust.io
    --users 100
    --spawn-rate 10
    --run-time 3m
  workerCommandSeed: --locustfile /lotest/src/locust_project_demo.py
  workerReplicas: 3
  configMap: test-map
