---
commitizen:
  annotated_tag: true
  bump_message: "bump(release): v$current_version → v$new_version"
  name: cz_conventional_commits
  tag_format: $major.$minor.$patch$prerelease
  update_changelog_on_bump: true
  version: 2.0.0
  version_files:
  - charts/locust-k8s-operator/Chart.yaml:appVersion
  - charts/locust-k8s-operator/Chart.yaml:version
