micronaut:
  application:
    name: locust-k8s-operator-integration-test
  http:
    client:
      read-timeout: 60s
      connect-timeout: 30s

logger:
  levels:
    com.locust: DEBUG
    io.fabric8: INFO
    org.testcontainers: INFO

integration-test:
  timeout:
    cluster-start: 300s
    operator-ready: 300s
    test-deployment: 180s
    test-execution: 120s
    cleanup: 180s
  resources:
    temp-dir: /tmp/locust-integration-test
    operator-image: locust-k8s-operator:integration-test
