name: 'Mark and close stale issues'
permissions:
  issues: write
  
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been for 30 days with no activity. Remove stale label or leave a comment, otherwise, this issue will be closed in 10 days.'
          days-before-stale: 30
          days-before-close: 10
          exempt-all-assignees: true
          exempt-issue-labels: 'good first issue'
